image: Visual Studio 2017
init:
  - set PATH=%PATH%;C:\Program Files (x86)\NSIS\bin
install:
  - git submodule update --init --recursive
build_script:
  - msbuild open-inspection-system.sln /p:Configuration=Release /p:Platform=x64
  - makensis installer.nsi
artifacts:
  - path: ois-installer-v*.exe
    name: ois-installer
